Fusion-Qa-Final/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Deliveries__c.object
<CustomObject>
    <description>Deliveries</description>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Bill To)</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliveries</label>
    <nameField>
        <label>Pack ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/classes/AccountAttachmentsController.cls
public class AccountAttachmentsController {
    
    @AuraEnabled
    public static map<string,list<sObject>> getAllRelatedAttachments(string accountID){
        set<id> parentIDs=new set<id>();
        map<string,list<sObject>> mpAttachment=new map<string,list<sObject>>();
        try{
            
            Account objAccount=[select id,(select id from contacts),(select id from Orders),(select id from Cases),(select id from ActivityHistories ORDER BY ActivityDate DESC , LastModifiedDate DESC  LIMIT 500),(select id from OpenActivities ORDER BY ActivityDate ASC , LastModifiedDate DESC  LIMIT 500),(select id from Opportunities)
                                ,(select id from Deliveries__r),(select id from Invoices__r)   
                                from Account where id=:accountID];
            
            
            if(objAccount!=null){                   
                parentIDs.add(objAccount.id);
                
                for(contact objContact: objAccount.contacts){
                    parentIDs.add(objContact.Id);
                }
                
                for(Case objCase: objAccount.Cases){
                    parentIDs.add(objCase.Id);
                }
                
                for(Order objOrder: objAccount.Orders){
                    parentIDs.add(objOrder.Id);
                }
                
                for(Opportunity objOpportunity: objAccount.Opportunities){
                    parentIDs.add(objOpportunity.Id);
                }
                
                for(ActivityHistory objTask: objAccount.ActivityHistories){
                    
                    parentIDs.add(objTask.Id);
                }
                
                for(OpenActivity objTask: objAccount.OpenActivities){
                    
                    parentIDs.add(objTask.Id);
                }
                
                for(Deliveries__c objDelivery: objAccount.Deliveries__r){
                    parentIDs.add(objDelivery.Id);
                }
                
                for(Invoice__c objInvoice: objAccount.Invoices__r){
                    parentIDs.add(objInvoice.Id);
                }
                
            }
            
            if(parentIDs.size()>0){
                system.debug('ParentIDS'+parentIDs);
                
                mpAttachment.put('Attachment',new list<attachment>([select id,Name,Body,BodyLength,ContentType,Description,
                                                                    ParentId,Parent.Name,CreatedDate,LastModifiedDate,
                                                                    LastModifiedById,LastModifiedBy.Name,CreatedById,CreatedBy.Name from attachment where ParentId in:parentIDs]));
                mpAttachment.put('File',new list<ContentDocumentLink>([SELECT ContentDocumentId,LinkedEntityId,LinkedEntity.Name,ContentDocument.ContentAssetId,
                                                                       ContentDocument.Title,ContentDocument.Description,
                                                                       ContentDocument.FileType,
                                                                       ContentDocument.CreatedDate,
                                                                       ContentDocument.LastModifiedDate,
                                                                       ContentDocument.LastModifiedBy.Name,
                                                                       ContentDocument.LastModifiedById,ContentDocument.CreatedById,ContentDocument.CreatedBy.Name   FROM ContentDocumentLink WHERE LinkedEntityId in :parentIDs]));
                
            }
            
        }catch(Exception ex){
            throw new AuraHandledException('Error occurred: ' + ex.getMessage());             
        }
        system.debug(mpAttachment.size());
        return mpAttachment;
    }
    
    @AuraEnabled
    public static void deleteRelatedAttachment(id attachmentId){        
        try{
            String objectName = attachmentId.getSObjectType().getDescribe().getName();            
            list<sObject> deleteList=database.query('select id from '+objectName+' where id=:attachmentId'); 
            delete deleteList;
        }
        catch(Exception ex){
            throw new AuraHandledException('Error occurred: ' + ex.getMessage());             
        }
    }
    
}