Fusion-Qa-Final/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Deliveries__c.object
<CustomObject>
    <description>Deliveries</description>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To)</relationshipLabel>
        <relationshipName>Deliveries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliveries</label>
    <nameField>
        <label>Pack ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/classes/BeforeTriggerDeliveryLine.cls
@isTest
public class BeforeTriggerDeliveryLine{
    @isTest static void DeliveryLineTest() {
        Account Acc  = new Account(Name = 'test');
        insert Acc;
    
        Deliveries__c deli = new Deliveries__c(Name ='del 1',Ship_To__c = Acc.id);
        insert deli;
        
        Delivery_Lines__c delLines = new Delivery_Lines__c(Name ='delline1',Deliveries__c = deli.id, QTY_Ordered__c  ='10.00');
        insert delLines;
        
        delLines = [select Id,QTY_Ordered__c from Delivery_Lines__c where Id=:delLines.Id ];
        system.assertEquals(delLines.QTY_Ordered__c,'10');
    }  
}