Fusion-Qa-Final/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>This is used to capture email during the business account creation.</description>
        <inlineHelpText>Test helptext</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SAPCustomerNumber__c</fullName>
        <description>This field holds the SAP customer number.</description>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Quote_Header__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Headers</relationshipLabel>
        <relationshipName>Quote_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Header</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/classes/QuoteViewHighlightPanelController.cls
public class QuoteViewHighlightPanelController {
    
    @AuraEnabled
    Public static string changeQuoteStatus(Id QuoteId){
        String message = QuoteCommonUtil.expireQuote(QuoteId);
        return message;
    }
    
    @AuraEnabled
   public static void margeCallout(string qutoeHeaderId)
   {
       List<account> aList = new List<Account>();
       Quote_Header__c qh = [select Account__c from Quote_Header__c where id =: qutoeHeaderId];
       Account a = [select id, name, Email__c, Phone, BillingStreet, BillingCity, BillingState, BillingPostalCode,BillingCountry, SAPCustomerNumber__c, (select id, name, Email__c, Phone, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry,  SAPCustomerNumber__c from ChildAccounts where recordType.Name = 'Ship to') from account where id =: qh.Account__c];
       System.debug('Account info --------->'+a);
     //  System.debug('Account Ship to Request--->'+a.ChildAccounts[0]);
       if(a.ChildAccounts.size() > 0)
       {
           ShipToResponse shipRes = AccountSAPCallOut.shipToCallOut(a.ChildAccounts[0]);
           SoldToResponse soldRes = AccountSAPCallOut.soldToCallout(a);
           AccountSAPCallOut.soldShipCallout(shipRes.BUSINESSPARTNER, soldRes.BUSINESSPARTNER);
           a.SAPCustomerNumber__c =soldRes.BUSINESSPARTNER;
           a.ChildAccounts[0].SAPCustomerNumber__c = shipRes.BUSINESSPARTNER;
           System.debug('Response SHip To---->'+a.ChildAccounts[0].SAPCustomerNumber__c);
           aList.add(a);
           aList.add(a.ChildAccounts[0]);
       }
       else
       {
           SoldToResponse soldRes = AccountSAPCallOut.soldToCallout(a);
           a.SAPCustomerNumber__c =soldRes.BUSINESSPARTNER;
           System.debug('Response Sold To---->'+a.SAPCustomerNumber__c);
           alist.add(a);


       }

       update aList;

   }

}