Fusion-Qa-Final/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Deliveries__c.object
<CustomObject>
    <description>Deliveries</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliveries</label>
    <nameField>
        <label>Pack ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/classes/TSTU_YetiSyncHelper.cls
@isTest
public with sharing class TSTU_YetiSyncHelper
{
    @isTest
    public static void test_createSalesOrderIdMap()
    {
        Test.startTest();
        Order__c ord = new Order__c();
        ord.Name = 'bogus';
        insert ord;
        Set<String> orderNumbers = new Set<String>();
        orderNumbers.add('bogus');
        Map<String, String> result = UTIL_YetiSyncHelper.createSalesOrderIdMap(orderNumbers);
        System.assert(result.size()==1);
        Test.stopTest();
    }

    @isTest
    public static void test_createDeliveryIdMap()
    {
        Test.startTest();
        Deliveries__c del = new Deliveries__c();
        del.Name = 'bogus';
        insert del;
        Set<String> delivNums = new Set<String>();
        delivNums.add('bogus');
        Map<String, String> result = UTIL_YetiSyncHelper.createDeliveryIdMap(delivNums);
        System.assert(result.size()==1);
        Test.stopTest();
    }

    @isTest
    public static void test_createInvoiceIdMap()
    {
        Test.startTest();
        Invoice__c inv = new Invoice__c();
        inv.Name = 'bogus';
        insert inv;
        Set<String> delivNums = new Set<String>();
        delivNums.add('bogus');
        Map<String, String> result = UTIL_YetiSyncHelper.createInvoiceIdMap(delivNums);
        System.assert(result.size()==1);
        Test.stopTest();
    }

    @isTest
    public static void test_getNotFoundAccountId()
    {
        List<sObject> errors = new List<sObject>();

        Test.startTest();
        // The first time we run this, it may not exist so it will be created.
        String resultId = UTIL_YetiSyncHelper.getNotFoundAccountId(errors);
        System.assert(String.isNotBlank(resultId));

        // The second time we run this, it should already be created and will
        // be returning the ID of the account it found.
        String expected = resultId;
        UTIL_YetiSyncHelper.notFoundAccount = null;
        resultId = UTIL_YetiSyncHelper.getNotFoundAccountId(errors);
        System.assert(String.isNotBlank(resultId) && resultId == expected);
        Test.stopTest();
    }

    @isTest
    public static void test_buildAddress()
    {
        Test.startTest();
        String expected = 'john doe\n' +
            '123 sesame st\n' +
            'nowhere, 45342, USA';
        String result = UTIL_YetiSyncHelper.buildAddress('john',
            'doe',
            '123 sesame st',
            'nowhere',
            '45342',
            'USA');
        System.assert(result == expected);
        Test.stopTest();
    }

    @isTest
    public static void test_customPricebook()
    {
        Test.startTest();
        String dealerPricebook = UTIL_YetiSyncHelper.dealerCustomPricebook;
        Pricebook2 newPricebook = new Pricebook2();
        newPricebook.Name = dealerPricebook;
        insert newPricebook;

        Pricebook2 customPricebook = UTIL_YetiSyncHelper.getCustomPricebook();
        Test.stopTest();

        System.assertEquals(dealerPricebook, customPricebook.Name);
    }
}