Fusion-Qa-Final/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>This is used to capture email during the business account creation.</description>
        <inlineHelpText>Test helptext</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/ProductOfIntrest__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>ProductOfIntrests</relationshipLabel>
        <relationshipName>ProductOfIntrests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Roadie 20</fullName>
                </value>
                <value>
                    <fullName>Tundra 35</fullName>
                </value>
                <value>
                    <fullName>Tundra 45</fullName>
                </value>
                <value>
                    <fullName>Tundra 50</fullName>
                </value>
                <value>
                    <fullName>Tundra 65</fullName>
                </value>
                <value>
                    <fullName>Tundra 75</fullName>
                </value>
                <value>
                    <fullName>Tundra 105</fullName>
                </value>
                <value>
                    <fullName>Tundra 110</fullName>
                </value>
                <value>
                    <fullName>Tundra 125</fullName>
                </value>
                <value>
                    <fullName>Tundra 160</fullName>
                </value>
                <value>
                    <fullName>Tundra 210</fullName>
                </value>
                <value>
                    <fullName>Tundra 250</fullName>
                </value>
                <value>
                    <fullName>Tundra 350</fullName>
                </value>
                <value>
                    <fullName>Tundra 420</fullName>
                </value>
                <value>
                    <fullName>Hopper 20</fullName>
                </value>
                <value>
                    <fullName>Hopper 30</fullName>
                </value>
                <value>
                    <fullName>Hopper 40</fullName>
                </value>
                <value>
                    <fullName>Tank 45</fullName>
                </value>
                <value>
                    <fullName>Tank 85</fullName>
                </value>
                <value>
                    <fullName>Sherpa</fullName>
                </value>
                <value>
                    <fullName>Tundra 45 White</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ProductOfIntrest</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductOfIntrests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/classes/LeadConvert.cls
/*
*************************************************************
** Name: LeadConvert.apxc                        	       **
** Copyright notice: 									   **
** YETI Coolers										       **
*************************************************************
** Purpose:                  							   **
** Lead Convert to Account, Contacts and Opportunity       **
*************************************************************
** History:                                                **
************************************************************* 
** VERSION AUTHOR DATE DETAIL RELEASE/CSR                  **
** 1.0 - Satesh Makineni 08/17/2018 INITIAL DEVELOPMENT    **
** 2.0 -                                                   **
*************************************************************
*/

public class LeadConvert {
    @AuraEnabled
    public static List<Account> checkAccount(ID recId){
        String leadName;
         String CompanyName;
        List<Account> accList = new List<Account>();
        List<Lead> leadList = [SELECT Name, Company, email FROM lead WHERE id= :recId];
        if(leadList != null && leadList.size() > 0){
            leadName=leadList[0].Name; 
            CompanyName = leadList[0].Company;
        }
        leadName = '%' + leadName + '%';
        CompanyName = '%' + CompanyName + '%';
        accList =  [SELECT id, name, Owner.Name, phone FROM account WHERE Email__c =: leadList[0].email OR name Like: leadName or name Like: CompanyName LIMIT 1000]; 
        System.debug(accList);
        return accList;
    }
    
    @AuraEnabled
    public static List<Contact> checkContact(ID accId){
        account a = [select id, ParentId, (select id from ChildAccounts)from account where id =: accId];
        List<id> idList = new List<id>();
        idList.add(accId);
        if(a.ParentId != null)
        {
            idList.add(a.ParentId);
        }
        for(account ca : a.ChildAccounts)
        {
            idList.add(ca.id);
        }
        List<contact> conList = new List<contact>();
        conList = [select id, firstName, lastName, Phone, email from contact where accountId in: idList];
        return conList;
    }
    
    @AuraEnabled
    public static List<id> convertLead(ID recId, string accId, string conId)
    {
        List<id> idList = new List<id>();
        // lead l = [select name,CurrencyIsoCode, (select id,Products__c,CurrencyIsoCode from ProductOfIntrests__r) from lead where id =: recId];
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(recId);
        
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus('Converted');
        lc.setOwnerId(userinfo.getUserId());
        
        if(accId != '')
        {
            lc.setAccountId(accId);
        }
        
        if(conId != '')
        {
            lc.setContactId(conId);
        }
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        
        idList.add(lcr.getAccountId());
        idList.add(lcr.getContactId());
        idList.add(lc.getOpportunityId());
        
      
        system.debug('idList ' + idList);
        return idList;
    }
    
}