Fusion-Qa-Final/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>This is used to capture email during the business account creation.</description>
        <inlineHelpText>Test helptext</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MaterialID__c</fullName>
        <externalId>true</externalId>
        <label>MaterialID</label>
        <length>34</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLocation__c</fullName>
        <label>ProductLocation</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>category__c</fullName>
        <label>category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Stock</fullName>
                </value>
                <value>
                    <fullName>NonCustom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/ProductOfIntrest__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>ProductOfIntrests</relationshipLabel>
        <relationshipName>ProductOfIntrests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Roadie 20</fullName>
                </value>
                <value>
                    <fullName>Tundra 35</fullName>
                </value>
                <value>
                    <fullName>Tundra 45</fullName>
                </value>
                <value>
                    <fullName>Tundra 50</fullName>
                </value>
                <value>
                    <fullName>Tundra 65</fullName>
                </value>
                <value>
                    <fullName>Tundra 75</fullName>
                </value>
                <value>
                    <fullName>Tundra 105</fullName>
                </value>
                <value>
                    <fullName>Tundra 110</fullName>
                </value>
                <value>
                    <fullName>Tundra 125</fullName>
                </value>
                <value>
                    <fullName>Tundra 160</fullName>
                </value>
                <value>
                    <fullName>Tundra 210</fullName>
                </value>
                <value>
                    <fullName>Tundra 250</fullName>
                </value>
                <value>
                    <fullName>Tundra 350</fullName>
                </value>
                <value>
                    <fullName>Tundra 420</fullName>
                </value>
                <value>
                    <fullName>Hopper 20</fullName>
                </value>
                <value>
                    <fullName>Hopper 30</fullName>
                </value>
                <value>
                    <fullName>Hopper 40</fullName>
                </value>
                <value>
                    <fullName>Tank 45</fullName>
                </value>
                <value>
                    <fullName>Tank 85</fullName>
                </value>
                <value>
                    <fullName>Sherpa</fullName>
                </value>
                <value>
                    <fullName>Tundra 45 White</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ProductOfIntrest</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductOfIntrests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Quote_Header__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Headers</relationshipLabel>
        <relationshipName>Quote_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quote Headers</relationshipLabel>
        <relationshipName>Quote_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ItemNumberToCapture__c</fullName>
        <label>ItemNumberToCapture</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Headers</relationshipLabel>
        <relationshipName>Quote_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Header</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Quote_Item_Level__c.object
<CustomObject>
    <fields>
        <fullName>CategorySection__c</fullName>
        <label>CategorySection</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stock</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>NonCustom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialID__c</fullName>
        <label>MaterialID</label>
        <length>34</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductUrl__c</fullName>
        <label>ProductUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Header</label>
        <referenceTo>Quote_Header__c</referenceTo>
        <relationshipLabel>Quote Items</relationshipLabel>
        <relationshipName>Quote_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Item_Number__c</fullName>
        <label>Quote Item Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Quote Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/classes/CreateQuote.cls
public class CreateQuote {
     @AuraEnabled
    public static List<Account> checkAccount(ID recId){
         String leadName;
         String CompanyName;
        List<Account> accList = new List<Account>();
        List<Lead> leadList = [SELECT Name, Company, email FROM lead WHERE id= :recId];
        if(leadList != null && leadList.size() > 0){
            leadName=leadList[0].Name; 
            CompanyName = leadList[0].Company;
        }
        leadName = '%' + leadName + '%';
        CompanyName = '%' + CompanyName + '%';
        accList =  [SELECT id, name, Owner.Name, phone FROM account WHERE Email__c =: leadList[0].email OR name Like: leadName or name Like: CompanyName LIMIT 1000]; 
        System.debug(accList);
        return accList;
    }
    
    @AuraEnabled
    public static List<Contact> checkContact(ID accId){
        account a = [select id, ParentId, (select id from ChildAccounts)from account where id =: accId];
        List<id> idList = new List<id>();
        idList.add(accId);
        if(a.ParentId != null)
        {
            idList.add(a.ParentId);
        }
        for(account ca : a.ChildAccounts)
        {
            idList.add(ca.id);
        }
        List<contact> conList = new List<contact>();
        conList = [select id, firstName, lastName, Phone, email from contact where accountId in: idList];
        return conList;
    }
    
    @AuraEnabled
    public static Id convertLead(ID recId, string accId, string conId)
    {
        List<id> idList = new List<id>();
        lead l = [select name,CurrencyIsoCode, (select id,Products__c,CurrencyIsoCode, Qty__c from ProductOfIntrests__r) from lead where id =: recId];
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(recId);
        
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus('Converted');
        lc.setOwnerId(userinfo.getUserId());

        if(accId != '')
        {
            lc.setAccountId(accId);
        }
        
        if(conId != '')
        {
           lc.setContactId(conId);
        }
       
        Database.LeadConvertResult lcr = Database.convertLead(lc);
       
        idList.add(lcr.getAccountId());
        idList.add(lcr.getContactId());
        idList.add(lcr.getOpportunityId());
         System.debug('opportunity'+idList[2]);
        
        Quote_Header__c qh =  new Quote_Header__c(CurrencyIsoCode = l.CurrencyIsoCode, Account__c = idList[0], Contact__c = idList[1], Opportunity__c = idList[2], status__c = 'new');
        insert qh;
        idList.add(qh.id);

        Set<string> ProductNameList = new set<string>();
        
        for(ProductOfIntrest__c pi : l.ProductOfIntrests__r)
        {
           ProductNameList.add(pi.Products__c);
        }
        
        List<Product2> ProductList = [select id,name,ProductCode,Description,ProductLocation__c, MaterialID__c,category__c from Product2 where name in: ProductNameList];
		
        Map<string, Product2> proddMap = new Map<string, Product2>();
        for(Product2 p : ProductList){
            proddMap.put(p.name, p);
            
        }
        
        List<Quote_Item_Level__c> qiList =  new List<Quote_Item_Level__c>();
        	Integer lineItemNumber = 0;
        for(ProductOfIntrest__c pi : l.ProductOfIntrests__r)
        {
            lineItemNumber += 10;
            qiList.add( new Quote_Item_Level__c(
                								CurrencyIsoCode = pi.CurrencyIsoCode, 
                								Name = pi.Products__c,
                								Product_Code__c = proddMap.containsKey(pi.Products__c)? proddMap.get(pi.Products__c).ProductCode : '', 
                								Product_Description__c = proddMap.containsKey(pi.Products__c)? proddMap.get(pi.Products__c).Description : '',
                								ProductUrl__c = proddMap.containsKey(pi.Products__c)?proddMap.get(pi.Products__c).ProductLocation__c : '',
                								CategorySection__c = proddMap.containsKey(pi.Products__c)?proddMap.get(pi.Products__c).category__c : '',
                                                MaterialID__c = proddMap.containsKey(pi.Products__c)?proddMap.get(pi.Products__c).MaterialID__c : '',
                								Quantity__c = pi.Qty__c,Quote_Item_Number__c = String.valueOf(lineItemNumber),	
                								Quote_Header__c = qh.id));
        }
        
        if(qiList.size() > 0)
        {
            //system.debug('-- item number-->'+qiList[0].Quote_Item_Number__c+'--'+qiList[1].Quote_Item_Number__c);
            insert qiList;
        }
        system.debug('idList ' + idList);
        qh.ItemNumberToCapture__c = lineItemNumber;
        
        update qh;
        system.debug('qh--- ' + qh);
        return qh.id;
    }

}