Fusion-Qa-Final/src/objects/Artwork__c.object
<CustomObject>
    <fields>
        <fullName>Art_BMP_URL__c</fullName>
        <label>Art BMP URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlatImage__c</fullName>
        <label>FlatImage</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Quote_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Header</label>
        <referenceTo>Quote_Header__c</referenceTo>
        <relationshipLabel>Artworks</relationshipLabel>
        <relationshipName>Artworks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Item</label>
        <referenceTo>Quote_Item_Level__c</referenceTo>
        <relationshipLabel>Artworks</relationshipLabel>
        <relationshipName>Artworks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPK__c</fullName>
        <label>UPK</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ramsideloc__c</fullName>
        <label>ramsideloc</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Artwork</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Quote_Header__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Item__c</fullName>
        <label>Discount Item</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discountmeasure__c</fullName>
        <label>Discountmeasure</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Header</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/objects/Quote_Item_Level__c.object
<CustomObject>
    <fields>
        <fullName>CategorySection__c</fullName>
        <label>CategorySection</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stock</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>NonCustom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount_Item__c</fullName>
        <label>Discount Item</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discountmeasure__c</fullName>
        <label>Discountmeasure</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaterialID__c</fullName>
        <label>MaterialID</label>
        <length>34</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Measure__c</fullName>
        <label>Measure</label>
        <length>34</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductUrl__c</fullName>
        <label>ProductUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Header</label>
        <referenceTo>Quote_Header__c</referenceTo>
        <relationshipLabel>Quote Items</relationshipLabel>
        <relationshipName>Quote_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Item_Number__c</fullName>
        <label>Quote Item Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPK__c</fullName>
        <label>UPK</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fusion-Qa-Final/src/classes/QuoteTabController.cls
public class QuoteTabController {
    
    @AuraEnabled
    public static List<Quote_Item_Level__c> getRelatedLineItems(Id QuoteId){
        List<Quote_Item_Level__c> lineitems = [select Id, Name,ProductUrl__c,UPK__c,Discountmeasure__c,Discount_Item__c, Product_Description__c,Quote_Item_Number__c,Unit_Rate__c,Tax__c,Measure__c,MaterialID__c,Quantity__c,Item__c,CategorySection__c,(Select Id,Name,FlatImage__c,Art_BMP_URL__c,ramsideloc__c from Artworks__r ) from Quote_Item_Level__c where Quote_Header__c =:QuoteId];
      //Quote_Header__c quoteObj = [select Id,(select Id, Name,ProductUrl__c, Product_Description__c from Quote_Items__r) from Quote_Header__c where Id =: QuoteId limit 1];
      //return quoteObj.Quote_Items__r;
      return lineitems;
    }

}